### ISSUE TITLE
Building Errors (Ubuntu 16.04)

### ISSUE THREAD

**Issue by exploshot** [Nur1Labs/CryptonoteEvo-GUI#5]
Did you successfully build that GUI? There some Qt Errors:

**build/ui_overviewframe.h:32:16: error: 'BalanceOverviewFrame' in namespace 'WalletGUI' does not name a type WalletGUI::BalanceOverviewFrame *m_balanceOverviewFrame;**_

**Comment by SoraKohaku** [comment]
Will try after that checking on core codes.

**Comment by ShiroYutha** [comment]
there instruction. can you follow up?
